### ISSUE TITLE
json and jsonb are not supported types on postgres

### ISSUE THREAD

**Issue by fsarwari** [CrunchyData/pgCompare#29]
**Describe the issue:**
A table has a column with type json or jsonb can not be used.

```
[2024-12-12 19:58:14] [SEVERE ] [Reconcile-target-c6-t0  ] Database error:  ERROR: function length(jsonb) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 230
```

```
[2024-12-12 20:06:41] [SEVERE ] [Reconcile-target-c12-t0 ] Database error:  ERROR: function length(json) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 229
```

**Describe the expected behavior:**
All types other than unsupported types should work.

**Tell us about your environment:**
Postgres 12.19 & Postgres 16.4 & Aurora Postgres 16.4 

Source Database:
- RDBMS Type: Postgres 
- Version: 12

Target Database:
- RDBMS Type: Postgres
- Version: 16

Source Table DDL:

Target Table DDL:

**Comment by cbrianpace** [comment]
Try to modify the column expression in the column map (dc_table_column_map table, map_expression column).  For example, assuming the column name is `myjson` in the map_expression you have just `myjson`.  Modify this to be `myjson::text` and this should resolve the issue.  If you are on an older version of pgCompare, the expression is stored in the dc_table.column_map column.  Same change there just stored in a json object, cast the type to text.  

Let me know if that fixes the issue.

**Comment by fsarwari** [comment]
Thank you @cbrianpace!  That worked for both type json and jsonb.

```
pgcompare=# select map_expression  from dc_table_column_map where column_name = 'data' ;
                           map_expression
---------------------------------------------------------------------
 coalesce(case when length(data)=0 then ' ' else data::text end,' ')
 coalesce(case when length(data)=0 then ' ' else data::text end,' ')
(2 rows)
pgcompare=# update dc_table_column_map set map_expression = 'coalesce(case when length(data::text)=0 then '' '' else data::text end,'' '')' where column_name = 'data';
UPDATE 2
```
